### ISSUE TITLE
Only first two commands execute with BB firmware v1.3

### ISSUE THREAD

**Issue by joshschmelzle** [jsnyder81/BB_WiFi_Diagnostics_OSX#2]
I had issues with my BB only executing the first two commands of the payload. The solution was to upgrade the BB firmware. Created this issue with hope that it may help others running into issues with this payload.

- Target device: MBP 2015 running macOS Catalina v10.15.1
- BB firmware:  v1.3_267

To demonstrate, I took out the `QUACK STRING "clear"` and `QUACK GUI q` from the payload:

![BB output running v1.3](https://i.imgur.com/PPu63t1.png)

Only 2 of 5 files would end up in the loot. 

![BB loot running v1.3](https://i.imgur.com/0DAGvwM.png)

# Solution

Upgrade BB firmware.

**Comment by jsnyder81** [comment]
This is by design, due to some changes in how the bash bunny handles payloads
Added some verbiage to the README.MD to address version requirements.
